# config.toml

[server]
host = "0.0.0.0"
port = 5000

[device]
com_port = "/dev/ttyUSB0"
baud_rate = 9600
timeout = 1

[logging]
log_level = "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
log_file = "server.log"
